### ISSUE TITLE
Adding consumer using '--flow-control' causes panic

### ISSUE THREAD

**Issue by rickardgranberg** [nats-io/natscli#119]
I'm using the NATS CLI to add a consumer in a script so I don't want any interactivity. When I run the following command:

`
nats con add STREAM CONSUMER --filter 'subject' --pull --deliver=last --replay=instant --max-deliver=-1 --max-pending=0 --flow-control
`

I get:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x80b073]

goroutine 1 [running]:
gopkg.in/alecthomas/kingpin%2ev2.(*boolValue).Set(0xc000220698, 0xdbcd9f, 0x4, 0xc, 0x13d8d00)
        /Users/rip/go/pkg/mod/gopkg.in/alecthomas/kingpin.v2@v2.2.6/values_generated.go:24 +0x73
gopkg.in/alecthomas/kingpin%2ev2.(*Application).setValues(0xc0004dc000, 0xc000432090, 0x0, 0x0, 0xc, 0xc000432090, 0x0)
        /Users/rip/go/pkg/mod/gopkg.in/alecthomas/kingpin.v2@v2.2.6/app.go:488 +0x469
gopkg.in/alecthomas/kingpin%2ev2.(*Application).Parse(0xc0004dc000, 0xc000114830, 0xc, 0xc, 0x1, 0xc000220550, 0x0, 0x1)
        /Users/rip/go/pkg/mod/gopkg.in/alecthomas/kingpin.v2@v2.2.6/app.go:199 +0xf0
main.main()
        /Users/rip/go/src/github.com/nats-io/natscli/nats/main.go:109 +0x1587
```

It doesn't matter if I do `--flow-control`, `--flow-control=true` or `--flow-control=false`, the same error happens.
Omitting the `--flow-control` and answering the prompt does work however.

I am using NATS CLI version 0.0.22

**Comment by ripienaar** [comment]
Thanks, will look

**Comment by ripienaar** [comment]
Fixed by https://github.com/nats-io/natscli/pull/120
