### ISSUE TITLE
Issue backing up a memory store

### ISSUE THREAD

**Issue by ColinSullivan1** [nats-io/natscli#21]
1) Create a memory store named mem-test and publish a few messages.

```
 $ ./nats stream info mem-test
Information for Stream mem-test

Configuration:

             Subjects: foo
     Acknowledgements: true
            Retention: Memory - Limits
             Replicas: 1
       Discard Policy: Old
     Duplicate Window: 2m0s
     Maximum Messages: unlimited
        Maximum Bytes: unlimited
          Maximum Age: 0s
 Maximum Message Size: unlimited
    Maximum Consumers: unlimited

State:

            Messages: 4
               Bytes: 96 B
            FirstSeq: 1 @ 2020-12-22T16:46:03 UTC
             LastSeq: 4 @ 2020-12-22T16:46:07 UTC
    Active Consumers: 0

$ ./nats stream view mem-test
[1] Subject: foo Received: 2020-12-22T09:46:03-07:00

hello

[2] Subject: foo Received: 2020-12-22T09:46:05-07:00

hello

[3] Subject: foo Received: 2020-12-22T09:46:05-07:00

hello

[4] Subject: foo Received: 2020-12-22T09:46:07-07:00

hello

09:57:23 Reached apparent end of data
```

2)  Attempt a backup...

```
$ ./nats stream backup mem-test mem-test-backup
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x159261b]

goroutine 1 [running]:
main.(*streamCmd).backupAction(0xc00016cb00, 0xc0001723f0, 0x0, 0x0)
	/Users/colinsullivan/Dropbox/go/src/github.com/nats-io/natscli/nats/stream_command.go:408 +0x85b
gopkg.in/alecthomas/kingpin%2ev2.(*actionMixin).applyActions(0xc000346cd8, 0xc0001723f0, 0x0, 0x0)
	/Users/colinsullivan/Dropbox/go/pkg/mod/gopkg.in/alecthomas/kingpin.v2@v2.2.6/actions.go:28 +0x6d
gopkg.in/alecthomas/kingpin%2ev2.(*Application).applyActions(0xc000332000, 0xc0001723f0, 0x0, 0x0)
	/Users/colinsullivan/Dropbox/go/pkg/mod/gopkg.in/alecthomas/kingpin.v2@v2.2.6/app.go:557 +0xdc
gopkg.in/alecthomas/kingpin%2ev2.(*Application).execute(0xc000332000, 0xc0001723f0, 0xc00034abc0, 0x2, 0x2, 0x0, 0x0, 0x0, 0x3)
	/Users/colinsullivan/Dropbox/go/pkg/mod/gopkg.in/alecthomas/kingpin.v2@v2.2.6/app.go:390 +0x8f
gopkg.in/alecthomas/kingpin%2ev2.(*Application).Parse(0xc000332000, 0xc000020060, 0x4, 0x4, 0x1, 0xc00013c418, 0x0, 0x1)
	/Users/colinsullivan/Dropbox/go/pkg/mod/gopkg.in/alecthomas/kingpin.v2@v2.2.6/app.go:222 +0x1fe
main.main()
	/Users/colinsullivan/Dropbox/go/src/github.com/nats-io/natscli/nats/main.go:92 +0x1387
```

**Comment by ripienaar** [comment]
Memory backups are not supported at present, I suspect they will be supported when clustering lands since snapshots is how replicas do updates.

I fixed a timing issue and added a test https://github.com/nats-io/natscli/pull/22
