### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Shonke** [nats-io/natscli#379]
**Problem:**
When I used natscli, it crashed. He should show up 100%
This should be related to `pubbatch`. When I adjust it, it performs differently.

```
# nats bench test -s test1.dev:4222 --msgs=1000000 --js --size=1024 --pubbatch=201 --sub=1 --pub=1
22:28:30 JetStream ephemeral ordered push consumer mode, subscribers will not acknowledge the consumption of messages
22:28:30 Starting JetStream benchmark [subject=test, msgs=1,000,000, msgsize=1.0 KiB, pubs=1, subs=1, js=true, stream=benchstream, storage=memory, syncpub=false, pubbatch=201, jstimeout=30s, pull=false, consumerbatch=100, push=false, consumername=natscli-bench, replicas=1, purge=false, pubsleep=0s, subsleep=0s]
22:28:30 Starting subscriber, expecting 1,000,000 messages
22:28:30 Starting publisher, publishing 1,000,000 messages
Consuming     5s [===========================================================================================================================================================================>] 100%
Publishing    5s [===========================================================================================================================================================================>] 100%
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xc317d0]

goroutine 101 [running]:
github.com/nats-io/natscli/cli.jsPublisher({{0x7ffdbaa99d96, 0x4}, 0x1, 0x1, 0xf4240, 0x400, {0x0, 0x0}, 0x0, 0x0, ...}, ...)
	/Users/rip/go/src/github.com/nats-io/natscli/cli/bench_command.go:456 +0x610
github.com/nats-io/natscli/cli.(*benchCmd).runPublisher(0xc00026e340, 0xc0005001b0, 0xc000518600, 0xc0004006e4, 0xc000400730, 0xf4240, 0x0)
	/Users/rip/go/src/github.com/nats-io/natscli/cli/bench_command.go:540 +0x325
created by github.com/nats-io/natscli/cli.(*benchCmd).bench
	/Users/rip/go/src/github.com/nats-io/natscli/cli/bench_command.go:349 +0x3018
```

**What I have tried so far:**
```
pubbatch=200  -> No crash
pubbatch=201  -> Crash
pubbatch=300  -> Crash
pubbatch=399  -> Crash
pubbatch=400  -> No crash
```

I used the latest version:
https://github.com/nats-io/natscli/releases/download/v0.0.30/nats-0.0.30-linux-amd64.zip

**Possible Workaround:**
I don't know what to do

**Comment by ripienaar** [comment]
https://github.com/nats-io/natscli/pull/381
