### ISSUE TITLE
consumer cluster step-down failed on stuck push consumer

### ISSUE THREAD

**Issue by k15r** [nats-io/natscli#774]
Description:

on a 3 node nats cluster `2.9.15` (with jetstream enabled) a push consumer got stuck. To revive it i tried 
`nats consumer cluster step-down`

Instead of stepping down the consumer leader the nats cli failed with this error:
```
18:43:59 Requesting leader step down of "eventing-nats-0" in a 3 peer RAFT group
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x18 pc=0x104a932ac]

goroutine 1 [running]:
github.com/nats-io/natscli/cli.(*consumerCmd).leaderStandDown(0x14000356540, 0x0?)
	/Users/rip/go/src/github.com/nats-io/natscli/cli/consumer_command.go:254 +0x35c
github.com/choria-io/fisk.(*actionMixin).applyActions(0x0?, 0x104efe620?)
	/Users/rip/go/pkg/mod/github.com/choria-io/fisk@v0.2.1/actions.go:28 +0x64
github.com/choria-io/fisk.(*Application).applyActions(0x140000be500?, 0x14000178000)
	/Users/rip/go/pkg/mod/github.com/choria-io/fisk@v0.2.1/app.go:761 +0xf4
github.com/choria-io/fisk.(*Application).execute(0x140000be500, 0x14000178000?, {0x1400012b640, 0x3, 0x4})
	/Users/rip/go/pkg/mod/github.com/choria-io/fisk@v0.2.1/app.go:599 +0x50
github.com/choria-io/fisk.(*Application).Parse(0x140000be500, {0x14000128130?, 0x1400006a900?, 0x140003ee750?})
	/Users/rip/go/pkg/mod/github.com/choria-io/fisk@v0.2.1/app.go:262 +0xec
github.com/choria-io/fisk.(*Application).MustParseWithUsage(0x140000be500, {0x14000128130, 0x5, 0x5})
	/Users/rip/go/pkg/mod/github.com/choria-io/fisk@v0.2.1/app.go:827 +0x34
main.main()
	/Users/rip/go/src/github.com/nats-io/natscli/nats/main.go:69 +0x2264
```

**Comment by ripienaar** [comment]
Thanks, really weird case where the server stopped thinking this consumer even was clustered at all. 

Fixed in https://github.com/nats-io/natscli/pull/775
